### ISSUE TITLE
README link for ImageNet 2012 Large Scale Visual Recognition Challenge seems to be broken

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-ResNet-50#11]
The link in the README for the ImageNet 2012 Large Scale Visual Recognition Challenge doesn't seem to work anymore http://www.image-net.org/challenges/LSVRC/2012/

**Comment by bdwyer2** [comment]
The entire `image-net.org` isn't working for me. I'll wait a few days to see if they fix this.

**Comment by bdwyer2** [comment]
@ptitzler the website is now working.
