### ISSUE TITLE
Container does not work offline

### ISSUE THREAD

**Issue by bdwyer2** [IBM/MAX-ResNet-50#14]
On the first prediction made to this container the file [imagenet_class_index.json](https://s3.amazonaws.com/deep-learning-models/image-models/imagenet_class_index.json) is downloaded. This is from [fchollet/deep-learning-models/imagenet_utils.py#L39-L41](https://github.com/fchollet/deep-learning-models/blob/master/imagenet_utils.py#L39-L41).

Because of this the container will not work offline.

Downloading the file during the docker build process and storing it in `~/.keras/models/imagenet_class_index.json` should fix this.

**Comment by bdwyer2** [comment]
CC @MLnick @ptitzler

**Comment by bdwyer2** [comment]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/19673623/49544788-985cd580-f890-11e8-96e6-cd9ab5a00694.png">

**Comment by ptitzler** [comment]
ah yes. good catch. There should be no runtime dependencies on artifacts stored "on the cloud"!
